#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with typescript (auto-locate tsc).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# tsc 探测：env → 常见安装目录
TSC="${TSC:-}"
if [ -z "$TSC" ]; then
  for c in \
    "C:/Users/Administrator/AppData/Local/hermes/hermes-agent/node_modules/typescript/bin/tsc" \
    "C:/Users/Administrator/AppData/Local/hermes/node/node_modules/typescript/bin/tsc" \
    "/c/Users/Administrator/AppData/Local/hermes/hermes-agent/node_modules/typescript/bin/tsc"; do
    if [ -f "$c" ]; then TSC="$c"; break; fi
  done
fi
if [ -z "$TSC" ] || [ ! -f "$TSC" ]; then
  echo "build: cannot locate tsc (set TSC env)" >&2
  exit 1
fi

# 链接编译期依赖（类型解析用），指向运行环境实际安装位置
DC="C:/Users/Administrator/AppData/Local/hermes/node/node_modules/@deepseek-ai/dsh"
DSH_NM="$DC/node_modules"
COORDIS="$DSH_NM/@deepseek-ai/cordis"
mkdir -p node_modules/@deepseek-ai
link_pkg() {
  local link="$1" target="$2"
  if [ ! -e "$target" ]; then echo "build: missing dep: $target" >&2; exit 1; fi
  node -e "
    const fs=require('fs'),path=require('path');
    fs.rmSync(process.argv[1],{recursive:true,force:true});
    fs.mkdirSync(path.dirname(process.argv[1]),{recursive:true});
    fs.symlinkSync(path.resolve(process.argv[2]),path.resolve(process.argv[1]),process.platform==='win32'?'junction':'dir');
  " "$link" "$target"
}
echo "=== Linking build deps ==="
link_pkg "node_modules/@deepseek-ai/cordis" "$COORDIS"
link_pkg "node_modules/@deepseek-ai/dsh-tools" "$DSH_NM/@deepseek-ai/dsh-tools"
link_pkg "node_modules/@deepseek-ai/dsh-llm" "$DSH_NM/@deepseek-ai/dsh-llm"
link_pkg "node_modules/@deepseek-ai/dsh-system-prompt" "$DSH_NM/@deepseek-ai/dsh-system-prompt"
link_pkg "node_modules/@deepseek-ai/schemastery" "$DSH_NM/@deepseek-ai/schemastery"
link_pkg "node_modules/@types/node" "$DSH_NM/@types/node"
# standard-schema（schemastery/dsh-tools 类型涉及）
if [ -d "$DSH_NM/@standard-schema" ]; then
  link_pkg "node_modules/@standard-schema" "$DSH_NM/@standard-schema" || true
fi

echo "=== Compiling src → lib ==="
node "$TSC" -p tsconfig.json
echo "=== Copying assets (scrapling_search.py) ==="
cp src/scrapling_search.py lib/scrapling_search.py
echo "=== Build complete ==="
